# Generated by Django 5.2.4 on 2025-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('category', models.CharField(blank=True, choices=[('comedy', 'Comedy'), ('fiction', 'Fiction'), ('education', 'Education'), ('comics', 'Comics')], default='education', max_length=100, null=True)),
                ('language', models.CharField(blank=True, choices=[('english', 'English'), ('hindi', 'Hindi'), ('kannada', 'Kannada')], default='english', max_length=50, null=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('total_copies', models.IntegerField(default=1)),
                ('available_copies', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=255)),
                ('cover_image_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
